baseURL: "https://jameshach.netlify.app/"
languageCode: "en-us"
title: The James Hach Blog
theme: PaperMod

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

enableRobotsTXT: true
enableGitInfo: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: The James Hach Blog
  description: "I'm James Hach. I developed this space so that you can learn more about me."
  keywords: [James Hach, Blog, Portfolio, Product Manager, PaperMod]
  author: James Hach
  # author: ["Me", "You"] # multiple authors
  images: ["jhcrop.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "jh16.png"
    favicon16x16: "jh16.png"
    favicon32x32: "jh32.png"
    apple_touch_icon: "jh152.png"
    safari_pinned_tab: "jh152.png"

  label:
    text: " "
    icon: jh152.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "jhcrop.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to THE James Hach blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/sammyisjames"
    - name: linkedin
      url: "https://www.linkedin.com/in/jameshach/"
    - name: github
      url: "https://github.com/jhach/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # editPost:
    # URL: "https://github.com/<path_to_repo>/content"
    # Text: "Suggest Changes" # edit text
    # appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
    gtm_id: "GTM-PBMD4W4"
    gtm_datalayer: "basic" 
menu:
  main:
    - identifier: archives
      name: archives 
      url: /archives/
      weight: 10
    # - identifier: categories
      # name: categories
      # url: /categories/
      # weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    # - identifier: example
      # name: example.org
      # url: https://example.org
      # weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
# markup:
  # highlight:
    # noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
